language: android
sudo: required
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3              # Same version as specified in build.gradle
    - android-28                      # SDK version
    - android-22                      # For Emulator
    - extra-android-m2repository
    - extra-google-m2repository
    - Extra-android-support
    - extra-google-google_play_services
    - addon-google_apis-google-27
    - sys-img-armeabi-v7a-android-22  # Android Image

  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

before_install:
 - chmod +x gradlew

before_script:
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew clean build -Pbuild=dev

# Disabling Upload apk temporarily
# after_success:
#  - chmod +x ./upload-apk.sh 
#  - ./upload-apk.sh 
